name: 自動發布資源包更新

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - assets/**
      - pack.mcmeta
      - pack.png

permissions:
  contents: write

jobs:
  Simple-Packer:
    name: 簡易資源包發布
    uses: TeamKugimiya/reusable-workflows/.github/workflows/Simple-ResourcePacker.yml@main
    with:
      resourcepack_file_name: "MMLP-CN-to-ZW"
      release_title_name: "簡轉繁資源包"
      force_include_files: |
        LICENSE
      git_version_replacer: true
      generate_time_replacer: true
