name: 自動發布資源包更新

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - MultiVersions/**

permissions:
  contents: write

jobs:
  Simple-Packer:
    name: 簡易多版本發布
    uses: TeamKugimiya/reusable-workflows/.github/workflows/Simple-MultiVersionPacker.yml@main
    with:
      resourcepack_file_name: "MMLP-CN-to-ZW"
      release_title_name: "簡轉繁多版本"
      generate_time_replacer: true
